### PR TITLE
Upgrade iOS SDK to version 2.5.2

### LINKED ISSUE #18: [iOS] Update OneSignal framework
When trying to update module's One Signal framework with the last one on their github repo, the app crashes when I send a notification and app is opened, or attempt to open the app from notification.
The message is:

```
-[TiApp application:didReceiveRemoteNotification:]: unrecognized selector sent to instance 0x1701f0900
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TiApp application:didReceiveRemoteNotification:]: unrecognized selector sent to instance 0x1701f0900'
```
Not sure what they've changed about it =/
Do you guys have a solution for this by any chance?
Thanks

### LINKED ISSUE #24: OneSignal iOS Native 2.4.X Update - NotificationServiceExtension
@williamrijksen We recently released version 2.4.0 of our SDK which uses a `NotificationServiceExtension`. Media attachments and action buttons now use a NotificationServiceExtension with mutable-content instead of content-available on iOS 10 for improved delivery reliability and speed. This fixes the issue where notifications with these features would not show if the app was force-quit by swiping it away.
https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.4.0

This also includes other bug fixes and improvements so I highly recommend updating. I am OneSignal's lead mobile SDK developer so feel free to ask me any questions if you need any help on updating.

**Update: (2017-03-31)**
2.5.0 has been released with some additional methods, bug fixes and additional improvements.

### PR DESCRIPTION
**Pull request by jvandijk**
Fix #18, #24

### CODE REVIEW

**Comment by williamrijksen** [comment]
@jvandijk Travis build breaks :(

**Comment by williamrijksen** [comment]
@jvandijk Introduces the following warning:
```
'IdsAvailable:' is deprecated: Please use getPermissionSubscriptionState or addSubscriptionObserver and addPermissionObserver instead.
```

Is it possible to solve this in this PR or would you like to create an new issue for this?

**Comment by williamrijksen** [comment]
Verified!

**Comment by chmiiller** [comment]
Great work guys! Is this issue with `IdsAvailable` fixed? Because I'm using it a lot! Thanks...

**Pull request merged**
