### PR TITLE
Updating OneSignalSDK to v3.10.1

### PR DESCRIPTION
**Pull request by jordansilva**
I've just updated OneSignal SDK from v3.8.0 to v.3.10.1 for Android everything seems fine!

### CODE REVIEW

**Comment by adriendillens** [comment]
@williamrijksen production apps need to be updated ASAP (Samsung & OnePlus on Android 8.0 / 8.1 don't receive notifications at all -> background app & killed app).
Fast module release will be really appreciated ;-)

**Comment by jordansilva** [comment]
@adriendillens did you have tested the last release using v3.8.0 onesignal SDK?

**Comment by adriendillens** [comment]
> @adriendillens did you have tested the last release using v3.8.0 onesignal SDK?

Yes of course, i'm using it for 3 months (onesignal 2.0.1 with android SDK 3.8.0)
Disable battery optimization on users devices doesn't resolve problem
In addition, users receive notifications from other apps that uses FCM / GCM instead of onesignal

**Comment by jordansilva** [comment]
@adriendillens Are you testing in which device? Because I've tested using Samsung devices and it is working.

**Comment by adriendillens** [comment]
@jordansilva 
not working : 
- Oneplus 5 (A5000) Android 8.1.0 -> no notification received
- Samsung (SM-A320FL) Android 8.0.0 -> only vibrate, but no notification visible
These devices owns to beta testers, i can't see the logs for now ...
But, it seems to be related to [#71](https://github.com/williamrijksen/com.williamrijksen.onesignal/issues/71)
Onesignal Android SDK update should fix these problems right ?

**Comment by jordansilva** [comment]
I'm not sure that will solve the problem.

I've tested (with this SDK update) on Motorola X2, Samsung S7, Samsung
S9, and Moto G4. Tested using Android 6, 7 and 8 versions.
Have you checked this last comment in this thread?
https://stackoverflow.com/a/42250725/2005273

Send me a private message tomorrow (in Hangouts) and I help you to test the module locally and we can check if the SDK update will fix this issue.

**Comment by adriendillens** [comment]
@jordansilva The last comment says that signed APK receive notifications.
My APK si signed and is on Play Store (open beta).
Have you another idea ?

**Comment by joshualambert** [comment]
@jordansilva Has this still been working without issues in production for you?

**Comment by jvandijk** [comment]
Closing in favor of #79

**Pull request closed without merging**
