### PR TITLE
Fix/depreciation ids available

### PR DESCRIPTION
**Pull request by williamrijksen**
## Context
Replaces the idsavailable function by the get getPermissionSubscriptionState. 
 - [getPermissionSubscriptionState iOS](https://documentation.onesignal.com/docs/ios-native-sdk#section--getpermissionsubscriptionstate-)
 - [getPermissionSubscriptionState Android](https://documentation.onesignal.com/docs/android-native-sdk#section--getpermissionsubscriptionstate-)

## How to test
 - build the module
 - add the following code to your test device/application
```js
        var onesignal = require('com.williamrijksen.onesignal');
        
        var state = onesignal.getPermissionSubscriptionState();
alert(JSON.stringify(state));
```
- Verify the outcome is as expected.

## Notes
 Blocked by #62 
This is a breaking change!

### CODE REVIEW

**Comment by williamrijksen** [comment]
@jvandijk Based on #62, a functional test is still required. Can we do that?

**Comment by frodfigu** [comment]
But... Where is the release 2.2.0 for Android? The actual 2.1.1... shows me onesignal.getPermissionSubscriptionState is not a function

Thank you!

**Comment by SquirrelMobile** [comment]
The 2.2.0 remove the depreciated idsAvailable without implement the remplacement method : getPermissionSubscriptionState, can we merge this PR ?

**Comment by SquirrelMobile** [comment]
[com.williamrijksen.onesignal-iphone-2.2.1.zip](https://github.com/williamrijksen/com.williamrijksen.onesignal/files/4538340/com.williamrijksen.onesignal-iphone-2.2.1.zip)
I've compile the module for iOS (since we need the last SDK version to remove the UIWebview error and stil need the player_id from OneSignal.

Use this code : 
```
var e = onesignal.getPermissionSubscriptionState();
Ti.API.log("--- getPermissionSubscriptionState " + JSON.stringify(e));
```

It return on abject like this : 

```
{
  "subscriptionStatus": {
    "userSubscriptionSetting": true,
    "subscribed": true,
    "userId": "THE PLAYER ID",
    "pushToken": "THE PUSH TOKEN"
  },
  "permissionStatus": {
    "status": 2,
    "provisional": false,
    "hasPrompted": true
  },
  "emailSubscriptionStatus": {
    "emailAddress": null,
    "emailUserId": null
  }
}

```

**Pull request closed without merging**
