### PR TITLE
 Added methods for both android, ios retrieveSubscribed(), retrievePl…

### PR DESCRIPTION
**Pull request by AbdullahFaqeir**
Added methods for both android, ios 

- retrieveSubscribed()
- retrievePlayerId()
- retrieveToken()

### CODE REVIEW

**Comment by chmiiller** [comment]
This looks cool! Thanks for opening it, I'm going to finish my work on the setExternalUserId for Android and can try to merge it all

**Comment by AbdullahFaqeir** [comment]
@chmiiller Glad I helped, please let me know if anything else came up or if I can help in anything else. Cheers!

**Comment by chmiiller** [comment]
Actually I have a question, do you know how can we update One Signal's Android SDK in the project?

**Comment by AbdullahFaqeir** [comment]
@chmiiller would you like to leave it for me to handle it once you finish? I don't mind!

**Review by chmiiller — APPROVED** [review]

**Comment by AbdullahFaqeir** [comment]
Thanks @chmiiller !
I'll work on updating the Android SDK now and submit a new PR.
P.S. I already updated the iOS SDK.

**Comment by chmiiller** [comment]
oh Sorry, I was so focused doing all of this work that I didn't see your replies before! Thanks for your support

**Pull request merged**
