### PR TITLE
- Updated Android OneSignal SDK to 3.15.1 - Realease 2.1.2 Android, 2…

### PR DESCRIPTION
**Pull request by AbdullahFaqeir**
- Updated Android OneSignal SDK to 3.15.1 
- Release 2.1.2 Android.
- Release 2.2.2 iOS.

### CODE REVIEW

**Comment by chmiiller** [comment]
Hey @AbdullahFaqeir thanks for this one, but I figured out how to update it and I'm making 2 new releases (like you did): one for iOS on version 2.2.2 and one for Android on version 2.1.2.
Besides the new One Signal SDKs, they merge my new setExternalUserId/removeExternalUserId methods + your "retrieve" methods. I think I will close this PR without merging it if you don't mind

**Comment by chmiiller** [comment]
These are the new releases: https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.1.2 on Android and
https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.2.2 on iOS

**Comment by AbdullahFaqeir** [comment]
@chmiiller good job, of course I don't mind, and please poke me if you needed any help updating this module in the feature. Again, glad I helped with this.

**Comment by chmiiller** [comment]
Awesome work! Thanks for it and we can talk more on Titanium Slack (ti-slack.slack.com)

**Comment by AbdullahFaqeir** [comment]
@chmiiller can you please send me an invitation? abdullah(@)devloops(.)net

**Pull request closed without merging**
